### ISSUE TITLE
Returning results with a relevancy score of 0 when sort field is passed

### ISSUE THREAD

**Issue by XigeTime** [swiftype/swiftype-app-search-javascript#61]
When passing a sort field, the client seems to be returning results with a relevancy score of 0. Should these not be excluded completely as they are not relevant to the search term?

We have a sort by price field. When selecting either low or high, it seems to be returning our most expensive, or inexpensive indexed product and doesn't check if the relevancy score is above 0.

**Comment by JasonStoltz** [comment]
Hi @XigeTime,

That's a great question an interesting observation. It does seem odd that results with a relevancy score of 0 should be excluded.

I'm going to close this issue because it is not related to the API client, but the API itself.

Could you please repost on https://discuss.elastic.co/c/app-search?
